CREATE TABLE gold_social_welfare (
    country_code            VARCHAR(3)       NOT NULL,
    country                 TEXT             NOT NULL,
    year                    INTEGER          NOT NULL,
    unemployment_total      DOUBLE PRECISION,
    unemployment_youth      DOUBLE PRECISION,
    youth_unemployment_gap  DOUBLE PRECISION,
    youth_gap_ratio         DOUBLE PRECISION,
    self_employed_pct       DOUBLE PRECISION,
    poverty_headcount       DOUBLE PRECISION,
    poverty_change_5yr      DOUBLE PRECISION,
    urban_pop_pct           DOUBLE PRECISION,
    urban_pop_growth        DOUBLE PRECISION,
    pop_density             DOUBLE PRECISION,
    log_pop_density         DOUBLE PRECISION,
    pop_growth              DOUBLE PRECISION,
    hcons_share             DOUBLE PRECISION,
    hcons_growth            DOUBLE PRECISION,
    trade_pct_gdp           DOUBLE PRECISION,
    income_group            TEXT,
    development_group       TEXT,
    completeness_score      DOUBLE PRECISION,
    run_id                  TEXT,
    run_date                DATE,
    loaded_at               TIMESTAMP,
    PRIMARY KEY (country_code, year)
);
