CREATE TABLE gold_crisis_risk (
    country_code            VARCHAR(3)       NOT NULL,
    country                 TEXT             NOT NULL,
    year                    INTEGER          NOT NULL,
    "SovDebtCrisis"         SMALLINT,
    "CurrencyCrisis"        SMALLINT,
    "BankingCrisis"         SMALLINT,
    crisis_composite        SMALLINT,
    crisis_any              SMALLINT,
    "REER_deviation"        DOUBLE PRECISION,
    spending_efficiency     DOUBLE PRECISION,
    "govdebt_GDP"           DOUBLE PRECISION,
    "fiscal_balance_GDP"    DOUBLE PRECISION,
    "rGDP_growth_YoY"       DOUBLE PRECISION,
    income_group            TEXT,
    development_group       TEXT,
    completeness_score      DOUBLE PRECISION,
    run_id                  TEXT,
    run_date                DATE,
    loaded_at               TIMESTAMP,
    PRIMARY KEY (country_code, year)
);
