from sqlalchemy import text
from src.core.database import engine

SQL_SCRIPT = """
CREATE TABLE IF NOT EXISTS analytics_gold_growth_dynamics (
    country_code VARCHAR(3),
    year INT,
    "rGDP_growth_YoY_actual" DOUBLE PRECISION,
    "rGDP_growth_YoY_trend" DOUBLE PRECISION,
    "rGDP_growth_YoY_residual" DOUBLE PRECISION,
    "rGDP_growth_YoY_slope" DOUBLE PRECISION,
    "rGDP_growth_YoY_intercept" DOUBLE PRECISION,
    "rGDP_growth_YoY_r2" DOUBLE PRECISION,
    "rGDP_growth_YoY_anomaly_score" DOUBLE PRECISION,
    "GDP_growth_YoY_actual" DOUBLE PRECISION,
    "GDP_growth_YoY_trend" DOUBLE PRECISION,
    "GDP_growth_YoY_residual" DOUBLE PRECISION,
    "GDP_growth_YoY_slope" DOUBLE PRECISION,
    "GDP_growth_YoY_intercept" DOUBLE PRECISION,
    "GDP_growth_YoY_r2" DOUBLE PRECISION,
    "GDP_growth_YoY_anomaly_score" DOUBLE PRECISION,
    "trend_deviation_actual" DOUBLE PRECISION,
    "trend_deviation_trend" DOUBLE PRECISION,
    "trend_deviation_residual" DOUBLE PRECISION,
    "trend_deviation_slope" DOUBLE PRECISION,
    "trend_deviation_intercept" DOUBLE PRECISION,
    "trend_deviation_r2" DOUBLE PRECISION,
    "trend_deviation_anomaly_score" DOUBLE PRECISION,
    "GDP_pc_growth_gap_actual" DOUBLE PRECISION,
    "GDP_pc_growth_gap_trend" DOUBLE PRECISION,
    "GDP_pc_growth_gap_residual" DOUBLE PRECISION,
    "GDP_pc_growth_gap_slope" DOUBLE PRECISION,
    "GDP_pc_growth_gap_intercept" DOUBLE PRECISION,
    "GDP_pc_growth_gap_r2" DOUBLE PRECISION,
    "GDP_pc_growth_gap_anomaly_score" DOUBLE PRECISION,
    "rolling_mean_5yr_actual" DOUBLE PRECISION,
    "rolling_mean_5yr_trend" DOUBLE PRECISION,
    "rolling_mean_5yr_residual" DOUBLE PRECISION,
    "rolling_mean_5yr_slope" DOUBLE PRECISION,
    "rolling_mean_5yr_intercept" DOUBLE PRECISION,
    "rolling_mean_5yr_r2" DOUBLE PRECISION,
    "rolling_mean_5yr_anomaly_score" DOUBLE PRECISION,
    PRIMARY KEY (country_code, year)
);

CREATE TABLE IF NOT EXISTS analytics_gold_fiscal_monetary (
    country_code VARCHAR(3),
    year INT,
    "govdebt_GDP_actual" DOUBLE PRECISION,
    "govdebt_GDP_trend" DOUBLE PRECISION,
    "govdebt_GDP_residual" DOUBLE PRECISION,
    "govdebt_GDP_slope" DOUBLE PRECISION,
    "govdebt_GDP_intercept" DOUBLE PRECISION,
    "govdebt_GDP_r2" DOUBLE PRECISION,
    "govdebt_GDP_anomaly_score" DOUBLE PRECISION,
    "fiscal_balance_GDP_actual" DOUBLE PRECISION,
    "fiscal_balance_GDP_trend" DOUBLE PRECISION,
    "fiscal_balance_GDP_residual" DOUBLE PRECISION,
    "fiscal_balance_GDP_slope" DOUBLE PRECISION,
    "fiscal_balance_GDP_intercept" DOUBLE PRECISION,
    "fiscal_balance_GDP_r2" DOUBLE PRECISION,
    "fiscal_balance_GDP_anomaly_score" DOUBLE PRECISION,
    "real_interest_rate_actual" DOUBLE PRECISION,
    "real_interest_rate_trend" DOUBLE PRECISION,
    "real_interest_rate_residual" DOUBLE PRECISION,
    "real_interest_rate_slope" DOUBLE PRECISION,
    "real_interest_rate_intercept" DOUBLE PRECISION,
    "real_interest_rate_r2" DOUBLE PRECISION,
    "real_interest_rate_anomaly_score" DOUBLE PRECISION,
    "inflation_gap_actual" DOUBLE PRECISION,
    "inflation_gap_trend" DOUBLE PRECISION,
    "inflation_gap_residual" DOUBLE PRECISION,
    "inflation_gap_slope" DOUBLE PRECISION,
    "inflation_gap_intercept" DOUBLE PRECISION,
    "inflation_gap_r2" DOUBLE PRECISION,
    "inflation_gap_anomaly_score" DOUBLE PRECISION,
    "inflation_cpi_actual" DOUBLE PRECISION,
    "inflation_cpi_trend" DOUBLE PRECISION,
    "inflation_cpi_residual" DOUBLE PRECISION,
    "inflation_cpi_slope" DOUBLE PRECISION,
    "inflation_cpi_intercept" DOUBLE PRECISION,
    "inflation_cpi_r2" DOUBLE PRECISION,
    "inflation_cpi_anomaly_score" DOUBLE PRECISION,
    "tax_revenue_pct_GDP_actual" DOUBLE PRECISION,
    "tax_revenue_pct_GDP_trend" DOUBLE PRECISION,
    "tax_revenue_pct_GDP_residual" DOUBLE PRECISION,
    "tax_revenue_pct_GDP_slope" DOUBLE PRECISION,
    "tax_revenue_pct_GDP_intercept" DOUBLE PRECISION,
    "tax_revenue_pct_GDP_r2" DOUBLE PRECISION,
    "tax_revenue_pct_GDP_anomaly_score" DOUBLE PRECISION,
    PRIMARY KEY (country_code, year)
);

CREATE TABLE IF NOT EXISTS analytics_gold_crisis_risk (
    country_code VARCHAR(3),
    year INT,
    "REER_deviation_actual" DOUBLE PRECISION,
    "REER_deviation_trend" DOUBLE PRECISION,
    "REER_deviation_residual" DOUBLE PRECISION,
    "REER_deviation_slope" DOUBLE PRECISION,
    "REER_deviation_intercept" DOUBLE PRECISION,
    "REER_deviation_r2" DOUBLE PRECISION,
    "REER_deviation_anomaly_score" DOUBLE PRECISION,
    "spending_efficiency_actual" DOUBLE PRECISION,
    "spending_efficiency_trend" DOUBLE PRECISION,
    "spending_efficiency_residual" DOUBLE PRECISION,
    "spending_efficiency_slope" DOUBLE PRECISION,
    "spending_efficiency_intercept" DOUBLE PRECISION,
    "spending_efficiency_r2" DOUBLE PRECISION,
    "spending_efficiency_anomaly_score" DOUBLE PRECISION,
    PRIMARY KEY (country_code, year)
);

CREATE TABLE IF NOT EXISTS analytics_gold_social_welfare (
    country_code VARCHAR(3),
    year INT,
    "poverty_headcount_actual" DOUBLE PRECISION,
    "poverty_headcount_trend" DOUBLE PRECISION,
    "poverty_headcount_residual" DOUBLE PRECISION,
    "poverty_headcount_slope" DOUBLE PRECISION,
    "poverty_headcount_intercept" DOUBLE PRECISION,
    "poverty_headcount_r2" DOUBLE PRECISION,
    "poverty_headcount_anomaly_score" DOUBLE PRECISION,
    "poverty_change_5yr_actual" DOUBLE PRECISION,
    "poverty_change_5yr_trend" DOUBLE PRECISION,
    "poverty_change_5yr_residual" DOUBLE PRECISION,
    "poverty_change_5yr_slope" DOUBLE PRECISION,
    "poverty_change_5yr_intercept" DOUBLE PRECISION,
    "poverty_change_5yr_r2" DOUBLE PRECISION,
    "poverty_change_5yr_anomaly_score" DOUBLE PRECISION,
    "hcons_growth_actual" DOUBLE PRECISION,
    "hcons_growth_trend" DOUBLE PRECISION,
    "hcons_growth_residual" DOUBLE PRECISION,
    "hcons_growth_slope" DOUBLE PRECISION,
    "hcons_growth_intercept" DOUBLE PRECISION,
    "hcons_growth_r2" DOUBLE PRECISION,
    "hcons_growth_anomaly_score" DOUBLE PRECISION,
    "unemployment_total_actual" DOUBLE PRECISION,
    "unemployment_total_trend" DOUBLE PRECISION,
    "unemployment_total_residual" DOUBLE PRECISION,
    "unemployment_total_slope" DOUBLE PRECISION,
    "unemployment_total_intercept" DOUBLE PRECISION,
    "unemployment_total_r2" DOUBLE PRECISION,
    "unemployment_total_anomaly_score" DOUBLE PRECISION,
    "youth_unemployment_gap_actual" DOUBLE PRECISION,
    "youth_unemployment_gap_trend" DOUBLE PRECISION,
    "youth_unemployment_gap_residual" DOUBLE PRECISION,
    "youth_unemployment_gap_slope" DOUBLE PRECISION,
    "youth_unemployment_gap_intercept" DOUBLE PRECISION,
    "youth_unemployment_gap_r2" DOUBLE PRECISION,
    "youth_unemployment_gap_anomaly_score" DOUBLE PRECISION,
    PRIMARY KEY (country_code, year)
);

CREATE TABLE IF NOT EXISTS analytics_gold_structural_composition (
    country_code VARCHAR(3),
    year INT,
    "GFCF_to_GDP_actual" DOUBLE PRECISION,
    "GFCF_to_GDP_trend" DOUBLE PRECISION,
    "GFCF_to_GDP_residual" DOUBLE PRECISION,
    "GFCF_to_GDP_slope" DOUBLE PRECISION,
    "GFCF_to_GDP_intercept" DOUBLE PRECISION,
    "GFCF_to_GDP_r2" DOUBLE PRECISION,
    "GFCF_to_GDP_anomaly_score" DOUBLE PRECISION,
    "GNI_to_GDP_actual" DOUBLE PRECISION,
    "GNI_to_GDP_trend" DOUBLE PRECISION,
    "GNI_to_GDP_residual" DOUBLE PRECISION,
    "GNI_to_GDP_slope" DOUBLE PRECISION,
    "GNI_to_GDP_intercept" DOUBLE PRECISION,
    "GNI_to_GDP_r2" DOUBLE PRECISION,
    "GNI_to_GDP_anomaly_score" DOUBLE PRECISION,
    "agri_va_share_actual" DOUBLE PRECISION,
    "agri_va_share_trend" DOUBLE PRECISION,
    "agri_va_share_residual" DOUBLE PRECISION,
    "agri_va_share_slope" DOUBLE PRECISION,
    "agri_va_share_intercept" DOUBLE PRECISION,
    "agri_va_share_r2" DOUBLE PRECISION,
    "agri_va_share_anomaly_score" DOUBLE PRECISION,
    "manuf_va_share_actual" DOUBLE PRECISION,
    "manuf_va_share_trend" DOUBLE PRECISION,
    "manuf_va_share_residual" DOUBLE PRECISION,
    "manuf_va_share_slope" DOUBLE PRECISION,
    "manuf_va_share_intercept" DOUBLE PRECISION,
    "manuf_va_share_r2" DOUBLE PRECISION,
    "manuf_va_share_anomaly_score" DOUBLE PRECISION,
    "food_bev_share_manuf_actual" DOUBLE PRECISION,
    "food_bev_share_manuf_trend" DOUBLE PRECISION,
    "food_bev_share_manuf_residual" DOUBLE PRECISION,
    "food_bev_share_manuf_slope" DOUBLE PRECISION,
    "food_bev_share_manuf_intercept" DOUBLE PRECISION,
    "food_bev_share_manuf_r2" DOUBLE PRECISION,
    "food_bev_share_manuf_anomaly_score" DOUBLE PRECISION,
    PRIMARY KEY (country_code, year)
);

CREATE TABLE IF NOT EXISTS analytics_clusters (
    year INT,
    country_code VARCHAR(3),
    cluster_id INT,
    method TEXT,
    PRIMARY KEY (year, country_code)
);
"""

def init_database():
    try:
        with engine.begin() as conn:
            conn.execute(text(SQL_SCRIPT))
        print("Database analytics tables created successfully.")
    except Exception as e:
        print(f"Failed to create tables: {e}")

if __name__ == "__main__":
    init_database()